language: rust

cache:
  - cargo

matrix:
  include:
    - os: linux
      rust: stable
    - os: linux
      rust: beta
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
    - os: osx
      rust: beta
    - os: osx
      rust: nightly

addons:
  apt:
    packages:
      - libwebkit2gtk-4.0-dev

# This saves doing CI builds twice on each PRs - uncomment this when merged into neutrino upstream repo
#branches:
#  only:
#    - "master"

script:
  - cargo test